import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from 'components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import NextThemeProvider from '@/components/NextThemeProvider'
import ReactQueryProvider from '@/components/ReactQueryProvider'


const inter = Inter({ subsets: ['latin'], variable: "--font-sans", })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ClerkProvider>
            <NextThemeProvider>
              <Navbar />
              {children}
            </NextThemeProvider>
          </ClerkProvider>
        </ReactQueryProvider>
      </body>
    </html>

  )
}
