import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from 'components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import NextThemeProvider from '@/components/NextThemeProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <NextThemeProvider>
              <Navbar />
              {children}
            </NextThemeProvider>
          </body>
        </html>
    </ClerkProvider>
  )
}
